### ISSUE TITLE
翻译里面的小bug

### ISSUE THREAD

**Issue by kexinlii** [ch3rub1m/api-design-guide#24]
https://google-cloud.gitbook.io/api-design-guide/she-ji-mo-shi#lie-chu-zi-ji-he 里面的例子应该是 `GET https://library.googleapis.com/v1/shelves/-/books?filter=xxx
`

**Comment by ch3rub1m** [comment]
多谢，已修复

**Comment by ch3rub1m** [comment]
多谢，已修复。
